In [ ]:
# Name: shreyas wani PRN: 25070123131
# Experiment 14
# Aim: Data Binning and Data formatting using Python

In [ ]:
import pandas as pd
import numpy as np
data = { 'Product': ['Laptop','Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'], 'Price': [55000, 20000, 30000, 2000, 8000, 45000],'Units_Sold':[25,60,35,80,50,15]}
df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
# Data Binning
bins1 = [0, 10000, 30000, 60000]
labels1 = ['Low','Medium', 'High']
df['Price_Category'] = pd.cut(df['Price'], bins=bins1, labels=labels1)
print(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [ ]:
# Binning Units Sold
bins2 = [0, 30, 60, 100]
labels2 = ['Low Sales','Medium Sales', 'High Sales']
df['Sales_Category'] = pd.cut(df['Units_Sold'], bins=bins2, labels=labels2)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low Sales
1      Mobile  20000          60         Medium   Medium Sales
2      Tablet  30000          35         Medium   Medium Sales
3  Headphones   2000          80            Low     High Sales
4  Smartwatch   8000          50            Low   Medium Sales
5      Camera  45000          15           High      Low Sales

In [ ]:
# Data Formatting
# Convert Data Type
print(df.dtypes)
df['Units_Sold'] = df['Units_Sold'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales_Category    category
dtype: object

In [ ]:
df

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000        25.0           High      Low Sales
1      Mobile  20000        60.0         Medium   Medium Sales
2      Tablet  30000        35.0         Medium   Medium Sales
3  Headphones   2000        80.0            Low     High Sales
4  Smartwatch   8000        50.0            Low   Medium Sales
5      Camera  45000        15.0           High      Low Sales

In [ ]:
# Convert Text to Uppercase
df['Product'] = df['Product'].str.upper()
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [ ]:
# Rounding Values: rounding values like for decimals it would round it to whole number
df['Price'] = df['Price'].round(2)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [ ]:
# Additional Operations
# Sort Data
sorted_df = df.sort_values(by= 'Price')
print(sorted_df)

      Product  Price  Units_Sold Price_Category Sales_Category
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales
0      LAPTOP  55000        25.0           High      Low Sales

In [ ]:
# Sort data in descending order
sorted_df1 = df.sort_values(by= 'Price', ascending=False)
print(sorted_df1)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
5      CAMERA  45000        15.0           High      Low Sales
2      TABLET  30000        35.0         Medium   Medium Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales

In [ ]:
# Display Unique Values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [ ]:
# Dataset: Food Delivery Orders
import pandas as pd
import numpy as np

data = {'Order_ID':['O1','O2','O3','O4','O5','O6','O7','O8'], 'Order_Value':[250,450,120,600,300,150,500,220], 'Delivery_Time':[30,45,25,60,35,20,50,28],'Distance_km':[5,8,3,10,6,2,9,4]}
df = pd.DataFrame(data)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       O1          250             30            5
1       O2          450             45            8
2       O3          120             25            3
3       O4          600             60           10
4       O5          300             35            6
5       O6          150             20            2
6       O7          500             50            9
7       O8          220             28            4

In [ ]:
# Binning Order Value
bins = [0, 200,400, 700]
labels = ['Low','Medium', 'High']
df['Order_Value_Category'] = pd.cut(df['Order_Value'], bins=bins, labels= labels)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category
0       O1          250             30            5               Medium
1       O2          450             45            8                 High
2       O3          120             25            3                  Low
3       O4          600             60           10                 High
4       O5          300             35            6               Medium
5       O6          150             20            2                  Low
6       O7          500             50            9                 High
7       O8          220             28            4               Medium

In [ ]:
# Binning Delivery Time
bins1 = [0, 25, 40, 60]
labels1= ['Late', 'On Time', 'Early']
df['Delivery_Time_Category'] = pd.cut(df['Delivery_Time'], bins=bins1, labels= labels1)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category  \
0       O1          250             30            5               Medium
1       O2          450             45            8                 High
2       O3          120             25            3                  Low
3       O4          600             60           10                 High
4       O5          300             35            6               Medium
5       O6          150             20            2                  Low
6       O7          500             50            9                 High
7       O8          220             28            4               Medium

  Delivery_Time_Category
0                On Time
1                  Early
2                   Late
3                  Early
4                On Time
5                   Late
6                  Early
7                On Time

In [ ]:
bins2 = [ 0, 4, 8, 10]
labels2= ['Short', 'Medium', 'High']
df['Distance_km_Category'] = pd.cut(df['Distance_km'], bins=bins2, labels= labels2)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category  \
0       O1          250           30.0            5               Medium
1       O2          450           45.0            8                 High
2       O3          120           25.0            3                  Low
3       O4          600           60.0           10                 High
4       O5          300           35.0            6               Medium
5       O6          150           20.0            2                  Low
6       O7          500           50.0            9                 High
7       O8          220           28.0            4               Medium

  Delivery_Time_Category Distance_km_Category
0                On Time               Medium
1                  Early               Medium
2                   Late                Short
3                  Early                 High
4                On Time               Medium
5                   Late                Short
6                  Early                 High
7                On Time                Short

In [ ]:
print(df.dtypes)
df['Delivery_Time'] = df['Delivery_Time'].astype(float)
print(df.dtypes)

Order_ID                    object
Order_Value                  int64
Delivery_Time              float64
Distance_km                  int64
Order_Value_Category      category
Delivery_Time_Category    category
Distance_km_Category      category
dtype: object
Order_ID                    object
Order_Value                  int64
Delivery_Time              float64
Distance_km                  int64
Order_Value_Category      category
Delivery_Time_Category    category
Distance_km_Category      category
dtype: object

In [ ]:
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Time_Category,Distance_km_Category
0,O1,250,30.0,5,Medium,On Time,Medium
1,O2,450,45.0,8,High,Early,Medium
2,O3,120,25.0,3,Low,Late,Short
3,O4,600,60.0,10,High,Early,High
4,O5,300,35.0,6,Medium,On Time,Medium
5,O6,150,20.0,2,Low,Late,Short
6,O7,500,50.0,9,High,Early,High
7,O8,220,28.0,4,Medium,On Time,Short

In [ ]:
df['Order_Value_Category'] = df['Order_Value_Category'].str.upper()
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category  \
0       O1          250           30.0            5               MEDIUM
1       O2          450           45.0            8                 HIGH
2       O3          120           25.0            3                  LOW
3       O4          600           60.0           10                 HIGH
4       O5          300           35.0            6               MEDIUM
5       O6          150           20.0            2                  LOW
6       O7          500           50.0            9                 HIGH
7       O8          220           28.0            4               MEDIUM

  Delivery_Time_Category Distance_km_Category
0                On Time               Medium
1                  Early               Medium
2                   Late                Short
3                  Early                 High
4                On Time               Medium
5                   Late                Short
6                  Early                 High
7                On Time                Short

In [ ]:
sorted_df = df.sort_values(by= 'Distance_km')
print(sorted_df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category  \
5       O6          150           20.0            2                  LOW
2       O3          120           25.0            3                  LOW
7       O8          220           28.0            4               MEDIUM
0       O1          250           30.0            5               MEDIUM
4       O5          300           35.0            6               MEDIUM
1       O2          450           45.0            8                 HIGH
6       O7          500           50.0            9                 HIGH
3       O4          600           60.0           10                 HIGH

  Delivery_Time_Category Distance_km_Category
5                   Late                Short
2                   Late                Short
7                On Time                Short
0                On Time               Medium
4                On Time               Medium
1                  Early               Medium
6                  Early                 High
3                  Early                 High

In [ ]:
sorted_df = df.sort_values(by= 'Order_Value')
print(sorted_df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category  \
2       O3          120           25.0            3                  LOW
5       O6          150           20.0            2                  LOW
7       O8          220           28.0            4               MEDIUM
0       O1          250           30.0            5               MEDIUM
4       O5          300           35.0            6               MEDIUM
1       O2          450           45.0            8                 HIGH
6       O7          500           50.0            9                 HIGH
3       O4          600           60.0           10                 HIGH

  Delivery_Time_Category Distance_km_Category
2                   Late                Short
5                   Late                Short
7                On Time                Short
0                On Time               Medium
4                On Time               Medium
1                  Early               Medium
6                  Early                 High
3                  Early                 High

In [ ]:
# Count Of Categories
print(df['Order_Value_Category'].value_counts())
print(df)

Order_Value_Category
MEDIUM    3
HIGH      3
LOW       2
Name: count, dtype: int64
  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category  \
0       O1          250           30.0            5               MEDIUM
1       O2          450           45.0            8                 HIGH
2       O3          120           25.0            3                  LOW
3       O4          600           60.0           10                 HIGH
4       O5          300           35.0            6               MEDIUM
5       O6          150           20.0            2                  LOW
6       O7          500           50.0            9                 HIGH
7       O8          220           28.0            4               MEDIUM

  Delivery_Time_Category Distance_km_Category
0                On Time               Medium
1                  Early               Medium
2                   Late                Short
3                  Early                 High
4                On Time               Medium
5                   Late                Short
6                  Early                 High
7                On Time                Short